### ISSUE TITLE
Code needs Upgrade from Arduinojson V5 to V6

### ISSUE THREAD

**Issue by urako** [chrisjoyce911/esp32FOTA#7]
- Arduino board:  ESP32 Wrover 4M

- Arduino IDE version 1.8.9

- When installed with ArduinoJson V6.9.1 and V6.11.0 It does not work.

- Error:
esp32fota.cpp:215:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

StaticJsonBuffer<300> JSONBuffer;                         //Memory pool

esp32fota.cpp: In member function 'bool esp32FOTA::execHTTPcheck()':

esp32fota.cpp:215:29: error: expected primary-expression before '<' token

esp32fota.cpp:215:35: error: 'JSONBuffer' was not declared in this scope

-Comment
***It works with Arduinojson V5.13.5 but I need V 6.9.1 and higher for other use cases.

-What to do
How to upgrade your code from V5 to V6:
https://arduinojson.org/v6/doc/upgrade/
ArduinoJson 6 replaces the concept of JsonBuffer with the concept of JsonDocument

-So what is the problem just fix it Pal
Whell my codeFu is lacking. but I am going to tak a stab at it and hope I do not hurt myself 8/

**Comment by urako** [comment]
I see it is fixed before but not updated to Aduino's Library List
